version: '3.8'
services:
  nest-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - mynetwork
  mongo:
    restart: always
    image: mongo:latest
    volumes:
      - ./data:/data/db
    networks:
      - mynetwork
    ports:
      - 27027:27017
    environment:
      MONGO_USER: mongo
      MONGO_PASSWORD: 123

  # this is for e2e test
  # test-db:
  #   image: postgres:13
  #   ports:
  #     - 5435:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: nest
  #   networks:
  #     - mynetwork
networks:
  mynetwork:
